# Generated by Django 6.0.8 on 2026-09-12 19:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(default='Pakistan', max_length=80)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('tax_number', models.CharField(blank=True, help_text='NTN / GST / VAT', max_length=60)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('timezone', models.CharField(default='Asia/Karachi', max_length=60)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField(default=7)),
                ('business_type', models.CharField(choices=[('grocery', 'Grocery'), ('clothing', 'Clothing'), ('restaurant', 'Restaurant'), ('pharmacy', 'Pharmacy'), ('general', 'General Retail')], default='general', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'businesses',
            },
        ),
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prefix', models.CharField(default='INV', max_length=12)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('number_padding', models.PositiveSmallIntegerField(default=6)),
                ('footer_note', models.CharField(blank=True, default='Thank you for your purchase', max_length=255)),
                ('terms', models.TextField(blank=True)),
                ('show_logo', models.BooleanField(default=True)),
                ('show_tax_breakdown', models.BooleanField(default=True)),
                ('show_cashier_name', models.BooleanField(default=True)),
                ('paper_size', models.CharField(choices=[('80mm', '80mm thermal'), ('58mm', '58mm thermal'), ('A4', 'A4')], default='80mm', max_length=8)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_settings', to='businesses.business')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('is_head_office', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='businesses.business')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('business', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=60)),
                ('symbol', models.CharField(max_length=8)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=14)),
                ('is_base', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='businesses.business')),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'ordering': ['-is_base', 'code'],
                'unique_together': {('business', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=6)),
                ('is_inclusive', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='businesses.business')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
                'unique_together': {('business', 'code')},
            },
        ),
    ]
