# Generated by Django 6.0.8 on 2026-09-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('grocery', 'Grocery'), ('clothing', 'Clothing'), ('restaurant', 'Restaurant'), ('pharmacy', 'Pharmacy'), ('electronics', 'Electronics'), ('general', 'General Retail')], default='general', max_length=30),
        ),
    ]
