# Generated by Django 6.0.8 on 2026-09-12 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('pos', '0001_phase6_saas'),
        ('promotions', '0001_phase6_saas'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='membership_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='promotions.membershiptier'),
        ),
        migrations.AddField(
            model_name='customersale',
            name='pos_sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_sale', to='pos.sale'),
        ),
    ]
