# Generated by Django 6.0.8 on 2026-09-12 20:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=20)),
                ('prefix', models.CharField(max_length=12)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('padding', models.PositiveSmallIntegerField(default=6)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sequences', to='businesses.business')),
            ],
            options={
                'unique_together': {('business', 'key')},
            },
        ),
    ]
