# Generated by Django 6.0.8 on 2026-09-12 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('catalog', '0001_initial'),
        ('customers', '0002_phase6_saas'),
        ('pos', '0001_phase6_saas'),
        ('promotions', '0001_phase6_saas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='promotions.coupon'),
        ),
        migrations.AddField(
            model_name='sale',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sales', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='saleline',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_sale_lines', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='saleline',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos.sale'),
        ),
        migrations.AddField(
            model_name='saleline',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sale_lines', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_sale_payments', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.sale'),
        ),
        migrations.AlterUniqueTogether(
            name='sale',
            unique_together={('business', 'client_uuid'), ('business', 'number')},
        ),
    ]
